version: "3.9"

services:
  money_manager:
    image: htetlinmaung/money_manager
    restart: always
    ports:
      - "80:80"
    environment:
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      - ConnectionStrings__AzureSqlDb=Server=azuresql,1433;Database=MMDB;User ID=sa;Password=P@ssword;Encrypt=false;TrustServerCertificate=true;
      - JwtSettings__Secret=d8916dbfb041caebcfa66f0e36679ddcd8dca9c7fc8dac686551fd6515f906cd
  azuresql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=P@ssword
      - ACCEPT_EULA=1
    volumes:
      - azuresqldb:/var/opt/mssql

volumes:
  azuresqldb:
